spring.application.name=ms-perfiles
server.port=8086

# Configuracion de base de datos (variables de entorno para Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db-perfiles:3306/db_perfiles?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.cl.duoc.ms_perfiles=INFO
