spring.application.name=ms-gateway
server.port=8090

# --- Actuator (inspeccionar rutas) ---
management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=gateway
spring.cloud.gateway.server.webflux.actuator.verbose.enabled=true

# --- Rutas del Gateway ---

# Autenticador
spring.cloud.gateway.server.webflux.routes[0].id=ms-autenticador
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTENTICADOR_URL:http://ms-autenticador:8080}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/autenticador/**

# Catalogo
spring.cloud.gateway.server.webflux.routes[1].id=ms-catalogo
spring.cloud.gateway.server.webflux.routes[1].uri=${CATALOGO_URL:http://ms-catalogo:8081}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/catalogo/**

# Devoluciones
spring.cloud.gateway.server.webflux.routes[2].id=ms-devoluciones
spring.cloud.gateway.server.webflux.routes[2].uri=${DEVOLUCIONES_URL:http://ms-devoluciones:8082}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/devoluciones/**

# Ebooks
spring.cloud.gateway.server.webflux.routes[3].id=ms-ebooks
spring.cloud.gateway.server.webflux.routes[3].uri=${EBOOKS_URL:http://ms-ebooks:8083}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/ebooks/**

# Inventario
spring.cloud.gateway.server.webflux.routes[4].id=ms-inventario
spring.cloud.gateway.server.webflux.routes[4].uri=${INVENTARIO_URL:http://ms-inventario:8084}
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/inventario/**

# Penalizaciones
spring.cloud.gateway.server.webflux.routes[5].id=ms-penalizaciones
spring.cloud.gateway.server.webflux.routes[5].uri=${PENALIZACIONES_URL:http://ms-penalizaciones:8085}
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/penalizaciones/**

# Perfiles
spring.cloud.gateway.server.webflux.routes[6].id=ms-perfiles
spring.cloud.gateway.server.webflux.routes[6].uri=${PERFILES_URL:http://ms-perfiles:8086}
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/perfiles/**

# Prestamos
spring.cloud.gateway.server.webflux.routes[7].id=ms-prestamos
spring.cloud.gateway.server.webflux.routes[7].uri=${PRESTAMOS_URL:http://ms-prestamos:8087}
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/prestamos/**

# Reservas
spring.cloud.gateway.server.webflux.routes[8].id=ms-reservas
spring.cloud.gateway.server.webflux.routes[8].uri=${RESERVAS_URL:http://ms-reservas:8088}
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/v1/reservas/**

# Sucursales
spring.cloud.gateway.server.webflux.routes[9].id=ms-sucursales
spring.cloud.gateway.server.webflux.routes[9].uri=${SUCURSALES_URL:http://ms-sucursales:8089}
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/v1/sucursales/**


eureka.client.service-url.defaultZone=http://ms-eureka:8761/eureka/
eureka.instance.prefer-ip-address=true