spring.application.name=ms-devoluciones
server.port=8082

# Configuracion de base de datos (variables de entorno para Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db-devoluciones:3306/db_devoluciones?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Feign Client - URL de ms-prestamos (variable de entorno para Docker)
prestamos.service.url=${PRESTAMOS_URL:http://ms-prestamos:8087}

# Timeouts Feign Client
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000

logging.level.cl.duoc.ms_devoluciones=INFO
